# Docker compose for quack_domains.
services:
    quack_domains:
        container_name: quack_domains
        # Use the local Dockerfile as an image.
        build: .
        # Use the host server's network so we can publish mDNS messages.
        network_mode: host 
        privileged: true # Allow access to the Docker socket.
        restart: always # Restart when the server restarts.
        volumes:
          # Allow access to the host's Avahi daemon.
          - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
          # Allow access to the host's DBus, used by Avahi.
          - /var/run/dbus:/var/run/dbus
          # Allow access to the host's Docker socket.
          - /run/docker.sock:/run/docker.sock:ro
