services:
    publish:
        container_name: publish
        build: .
        volumes:
          - /var/run/dbus:/var/run/dbus
          - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
        network_mode: host
        privileged: true
