services:
    publish:
        container_name: publish
        build: .
        network_mode: host
        privileged: true
        restart: always
        env_file: .env
        volumes:
          - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
          - /var/run/dbus:/var/run/dbus
