services:
    subdomains:
        container_name: subdomains
        build: .
        network_mode: host
        privileged: true
        restart: always
        volumes:
          - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
          - /var/run/dbus:/var/run/dbus
          - /run/docker.sock:/run/docker.sock:ro
