services:

  traefik:
    image: traefik
    container_name: traefik
    networks:
      - traefik_network
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    image: traefik/whoami
    container_name: example_whoami
    networks:
      - traefik_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`example.local`) || Host(`subdomain.example.local`)
      - traefik.http.routers.whoami.entrypoints=web

networks:
  traefik_network:
    name: traefik_network